  
SET @STARTDATE := '2011-06-20';
SET @ENDDATE := '2011-06-22';

SELECT COUNT(*) AS 'NUMBER OF BUGS OPEN' 
FROM BUGS
WHERE ( OPEN_DATE  <= STR_TO_DATE(@STARTDATE, '%Y-%M-%D') 
	AND CLOSE_DATE > STR_TO_DATE(@STARTDATE, '%Y-%M-%D')
) AND (
OPEN_DATE  <= STR_TO_DATE(@ENDDATE, '%Y-%M-%D') 
AND CLOSE_DATE > STR_TO_DATE(@ENDDATE, '%Y-%M-%D')) ;